### ISSUE TITLE
Doesn't work with Angular 5

### ISSUE THREAD

**Issue by sanket-t-shah** [Gullfaxi171/angular-azure-blob-service#1]
I just upgraded my code to Angular 5 and figured out that this is not compatible with that. Can you please upgrade the same and provide fix?

**Comment by Gullfaxi171** [comment]
i just released a new version replacing angular's Http Module by new HttpClient Module. It should work now, can you confirm ?

**Comment by sanket-t-shah** [comment]
It worked. Thanks for the quick response !!!
