### ISSUE TITLE
After Upload Is that Its returns the Blob image save URL

### ISSUE THREAD

**Issue by VivekIshir** [Gullfaxi171/angular-azure-blob-service#10]
HI Guys,
I am not sure, this Lib is going to serve my requirement. 
My requirement is simple to Upload Media File On Azure Blob

**Comment by VivekIshir** [comment]
Anybody have idea about, how to generate the 'sas' Token here

**Comment by VivekIshir** [comment]
Also facing issue with CORS, How we can fix this, Is there any support available ?

**Comment by VivekIshir** [comment]
@Maritims I am facing Authentication 
403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)

**Comment by Maritims** [comment]
@VivekIshir You will have to look into the documentation for generating the token and ensure for yourself that the token you generated is of the format that is expected by Azure.

**Comment by VivekIshir** [comment]
@Maritims Ok Thanks for Feedback.

**Comment by Gullfaxi171** [comment]
it can upload every type of file,
there is info about configuring cors in the readme.md

feel free to reopen if needed
