### ISSUE TITLE
Error call back not working 

### ISSUE THREAD

**Issue by Tirupathitemburu** [Gullfaxi171/angular-azure-blob-service#11]
Hi Team,
Positive flow working fine for me and whenever I am getting some error, error logging in the console. but call back not working

**Comment by VivekIshir** [comment]
@Tirupathitemburu Is there file Upload, working fine for you ?

**Comment by VivekIshir** [comment]
@Tirupathitemburu Could you share your Code, So I can assist you well.

**Comment by dwheaton** [comment]
The error callback wasn't being called. Here's a fix #13

**Comment by Gullfaxi171** [comment]
@dwheaton thanks for the PR

I just added it in the last release

I'm closing, feel free to reopen if not working
