### ISSUE TITLE
Support for Microsoft Azure Storage Emulator

### ISSUE THREAD

**Issue by Maritims** [Gullfaxi171/angular-azure-blob-service#3]
It would for testing purposes be quite handy to be able to tell the blobService that you want to use an address pointing to the local Azure Storage Emulator.

At first glance I believe it is necessary to change the generateBlobUrl() method in BlobService.ts

**Comment by Maritims** [comment]
@Gullfaxi171 I've added a pull request for this in https://github.com/Gullfaxi171/angular-azure-blob-service/pull/4

**Comment by Gullfaxi171** [comment]
@Maritims that's great ! i'll merge this and try to make a new release today

**Comment by Gullfaxi171** [comment]
just pushed a release including your PR ! it should be working now !

**Comment by Maritims** [comment]
That's awesome @Gullfaxi171! Thank you!
