### ISSUE TITLE
403 Preflight error And No 'Access Control -allow-origin'

### ISSUE THREAD

**Issue by RajeshNair123** [Gullfaxi171/angular-azure-blob-service#6]
I m getting the following errors when trying to upload the file:----

Failed to load resource: the server responded with a status of 403 ()
patient:1 Failed to load https://bajajdtstrg.blob.core.windows.net/h2h/7-GENERAL%20CONSENT%20FORM%20ENGLISH.docxflKqjaPuesqnAmIH1VvDwL0Eh7FJ7l1xqSOsU9ubbrD57U0Z1cAcQf3xKk4uf91IA9pI1CrN2K6fU8shJexvSw==&comp=block&blockid=YmxvY2stMDAwMDAw: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.10.71:4443' is therefore not allowed access. The response had HTTP status code 403.

192.168.10.71:4443 is my localip:port and i m using ng serve to host in it.
I tried to move code to the published server also but same errors. 

Even if its CORS,how will be change in the backend because there seems no settings to change in the azure blob account.

@Gullfaxi171 
@Maritims

**Comment by cbernth** [comment]
Check out step 6.1 at the bottom:
https://dmrelease.blob.core.windows.net/azurestoragejssample/samples/sample-blob.html

**Comment by Gullfaxi171** [comment]
Thanks !
I added your link in the readme, and also added more info about CORS
