### ISSUE TITLE
Update to Angular 6

### ISSUE THREAD

**Issue by BrummbQ** [Gullfaxi171/angular-azure-blob-service#9]
Hello,

Your package still has a dependency to Angular 5. Can you update to v6 please?

**Comment by BrummbQ** [comment]
nvm, issue with my installation

**Comment by BrummbQ** [comment]
Though for full rxjs 6 compatibility the imports must be adjusted: `Module not found: Error: Can't resolve 'rxjs/Rx' in '.../node_modules/angular-azure-blob-service/esm5'`

**Comment by Gullfaxi171** [comment]
Thanks !
i'm planning to upgrade to v6 next weekend

**Comment by Gullfaxi171** [comment]
migrated to angualr 6 in release 1.1.0
